
business_options = "Abattoirs",
"Access Equip/Hire & Plant",
"Accom",
"Aerial & Satelite Installers",
"Agricultural suppliers",
"Air Compressors & Equipment",
"Air Conditioning installers",
"Airports",
"Amusement Parks and Arcades",
"Anodisers",
"Architects",
"Armed Forces Sites",
"Audio Visual Services",
"Bakers - Plant/Manufacturing",
"Banks",
"Bathroom/Bedroom/Kitchen Installers",
"Boat Builders and Repairs",
"Boiler Servicing and repairs",
"Brewers",
"Brick & Concrete Plants",
"Builders Merchants",
"Building Societies",
"Burglar Alarms and Security Systems",
"Butcher/Meat/Wholesalers/Abattoirs",
"Building suppliers",
"Car Dealerships",
"Caravam Parks/Caravan Repairs & Service",
"Casinos",
"Catering Engineers and Equip",
"Ceilings - Suspended",
"Central Heating Equip",
"Chemical Mfrs and Suppliers",
"Cinemas",
"Civil Engineers",
"Cleaning Services",
"Closed Circuit TV Installers",
"Clock/Watch MFRS. And Suppliers",
"Computer networking & Cabling",
"Computer Services",
"Computer Systems",
"Conservatory Suppliers",
"Container Hire",
"Control Panel Mfrs",
"Conveyor Systems",
"Cooked Meat Manufacturers",
"Crane Hire",
"Dairy Manufacturers (Not Deliveries)",
"Dancing Schools",
"Day Nurseries",
"Department Stores",
"Discos (Suppliers & Mobile)",
"Distillers",
"DIY Shops",
"Door Mfrs - Industrial",
"Driving Ranges (Golf)",
"Ducting and Ductwork/Ventilation",
"Dust Extraction and Ventilation",
"Electric Motor Repairs",
"Electric Engineers",
"Electrical Contractors",
"Electrical Inspecting and Testing",
"Electroplaters",
"Engineering Machine Shops",
"Estate Agents",
"Exhibition Stand Contractors",
"Facilities Management",
"Fan and Blower Mfrs. And Suppliers",
"Farmers",
"Far Refiners",
"Fire Alarms and Extinguising Equip",
"Fish Farms",
"Fitness Equipment Suppliers",
"Foundries",
"Food Mfrs and Suppliers",
"Food Processing Equip & Machinery",
"Football Clubs",
"Fork Lift Truck Services",
"Frozen Food Mfrs and Wholesalers",
"Furniture Manufacturers",
"Further Education (Colleges)",
"Garage Doors (Electric)",
"Garden centres",
"Gas Engineers and Installers",
"Gates and Railings (electric)",
"Galvanisers",
"Generators - Suppliers and Mfrs",
"Glass Merchants",
"Golf Clubs",
"Government Offices",
"Guest Houses",
"Harbour Authorities",
"Health Authorities and service",
"Health Clubs and Fitness Centres",
"Heating Services - Industrial",
"Hire Services - Tool and Equip",
"Holiday Accommodation and Parks",
"Hose Fitting and Accessory Mfrs",
"Hospices",
"Hospitals",
"Hotels and Inns",
"Housing Associations and Trusts",
"Illuminated Sign Manufacturers",
"Interior Designers",
"Joinery Manufacturers",
"Jewellers",
"Kitchen & Bathroom fitters / suppliers",
"Landscape Gardeners",
"Laundries & Launderettes",
"Lawnmower Specialists",
"Leisure centres / Swimming pools & Gymnasiums",
"Libraries",
"Lift Engineers",
"Lift Mfrs and Repairs",
"Lifting Gear and Hire",
"Lighting consulatants",
"Lighting Installers & Erectors",
"Local Government",
"Loft Converters",
"Machine Tool Suppliers",
"Mintenance Services",
"Marinas",
"Market Gardeners",
"Marquee & Tent Hire (inc Mfrs & Suppliers)",
"Meat Product Mfrs and Suppliers",
"Mechanical Engineers",
"Mezzanine Floors",
"Mobility Equipment Suppliers",
"Motels",
"Museums",
"Night Clubs",
"Nurseries (Horticultural)",
"Nursing Homes and Nurseries",
"Office Fitters",
"Oil Fuel Dist and Suppliers",
"Paper Mills",
"Partitioning Services and Equip",
"Pet Foods Manufaturers",
"Plastic Moulders",
"Plumbers and Heating Engineers",
"Plumbers Merchants",
"Powder Coaters",
"Printers",
"Prisons",
"Property Management Services",
"Public Houses",
"Public Schools",
"Pumps and Plumbing Equip",
"Purchasing Groups & Cooperatives",
"Quarries",
"Race Courses",
"Rail Transport Services",
"Refrigeration Engineers",
"Refurbishment - Commercial Premises",
"Residential and Retirement Homes",
"Restaurants",
"Retailers (Shops of all kinds)",
"Riding Schools",
"Roller Shutters (electric)",
"Rugby Clubs",
"Satellite TV and Equip",
"Sauna and Steam Room Equip",
"Sausage Mfrs (food)",
"Sawmills",
"Schools & Colleagues",
"Security CCTV installers",
"Sectional Building Suppliers",
"Sheet Metal Workers",
"Ship Chandlers",
"Shop Fitting Suppliers",
"Shop Fitters",
"Shopping Centres",
"Shutter Mfrs",
"Sign Makers",
"Soft Drink Mfrs & Suppliers (inv Vending Machines)",
"Sound Equip Installations",
"Sport Club and Associations",
"Sports Grounds and Stadiums",
"Spring Manufacturers",
"Stair Lift Installers",
"Steel Fabrications",
"Street Lighting Companies",
"Sun Bed Equip",
"Supermarkets",
"Swimming Pool/Spa Dealers",
"Telecommunication Engineers and Equip",
"Tennis Court (Installation of Lighting)",
"Textile Engineers & Manufacturers",
"Theatres and Concert Hall",
"Timber Merchants",
"Trailer Mfrs and Suppliers",
"Transformers Mfrs",
"TV Services",
"Tyre Distributors",
"Uninterruptible Power Supplies (Mfrs & Suppliers)",
"Universities",
"Upholstery Manufacturers",
"Utility Companies",
"Vacuum Repairers & Servicing",
"Vending Machine (Suppliers & Manufacturers)",
"Ventilation Services",
"Video Services",
"Wallpaper Manufacturers",
"Wallpaper Manufacturers Repairers & Services",
"Waste Paper Merchants",
"Water Treatment Services",
"Welding Equipement Services",
"Wildlife Parks",
"Wine Bars",
"Woodworking Machinery Suppliers",
"Wool Processors",
"Wrough Ironworkers",
"Youth Hostels",
"Zoos"
